apiVersion: v1
kind: Pod
metadata:
  name: pod-1g
spec:
  containers:
  - name: test-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600000']
    volumeMounts:
    - name: test-volume
      mountPath: /mountpath1
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: pvc-1g
