apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: petclinic
  name: petclinic
spec:
  containers:
  - image: marygabry1508/petclinic
    name: petclinic
    ports:
    - containerPort: 8080
