apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: petclinic
  name: petclinic
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: petclinic
  type: LoadBalancer
